### ISSUE TITLE
Can't open savegame in app

### ISSUE THREAD

**Issue by JerichoTheCmplx** [efossvold/fallout2-save-editor#2]
when i try to open the file in app, says it isnt a compatible save game and has the error message (f17.offset not found)
![Screen Shot 2024-05-02 at 11 47 40 PM](https://github.com/efossvold/fallout2-save-editor/assets/168801594/7dc6f0df-8676-4db2-b6bb-6c1fdcde9b42)

**Comment by JerichoTheCmplx** [comment]
may it be because i edited where my spawning point is?

**Comment by efossvold** [comment]
hi, would you be able to attach you savegame file here?

**Comment by reseto** [comment]
Hello, I have the same problem. I have the Fallout2 from Steam patched with Restoration project from here
https://github.com/phobos2077/Fallout2_Restoration_Project
[SAVEGAME.zip](https://github.com/user-attachments/files/16597127/SAVEGAME.zip) -- file here, it's a plain save near the temple of trials, level 1.

Save Editor says 
`Cannot assign to read only property 'prefGameDifficulty' of object '#<Object>'` 
I tried building with `wails dev` but that does not produce any more debug logging.
According to tips such as

1. https://stackoverflow.com/questions/54413909/uncaught-typeerror-cannot-assign-to-read-only-property-of-object-object
2. https://stackoverflow.com/questions/57121773/typeerror-cannot-assign-to-read-only-property-exports-of-object-object-i?rq=3
3. https://github.com/orgs/react-hook-form/discussions/3715

I was trying to modify the `save-data.tsx` line 173, but that didn't help. I'm not sure where the immutable object gets created.
Thus far I only tried on Windows, I can try on Mac if you want.

**Comment by efossvold** [comment]
> Hello, I have the same problem. I have the Fallout2 from Steam patched with Restoration project from here https://github.com/phobos2077/Fallout2_Restoration_Project [SAVEGAME.zip](https://github.com/user-attachments/files/16597127/SAVEGAME.zip) -- file here, it's a plain save near the temple of trials, level 1.
> 
> Save Editor says `Cannot assign to read only property 'prefGameDifficulty' of object '#<Object>'` I tried building with `wails dev` but that does not produce any more debug logging. According to tips such as
> 
> 1. https://stackoverflow.com/questions/54413909/uncaught-typeerror-cannot-assign-to-read-only-property-of-object-object
> 2. https://stackoverflow.com/questions/57121773/typeerror-cannot-assign-to-read-only-property-exports-of-object-object-i?rq=3
> 3. https://github.com/orgs/react-hook-form/discussions/3715
> 
> I was trying to modify the `save-data.tsx` line 173, but that didn't help. I'm not sure where the immutable object gets created. Thus far I only tried on Windows, I can try on Mac if you want.

Thanks for reporting this issue @reseto. It is not related to the initial issue reported by @JerichoTheCmplx. Nevertheless, it should be fixed in the release [v1.1.1](https://github.com/efossvold/fallout2-save-editor/releases/tag/v1.1.1). That being said, I have no experience with the Restoration Project so I can't guarantee that the saves work with it. Neither is it within the scope of this editor to support it. Feel free to let me know if it worked out though 😊
